
    // unexpire default passwords
    set $namespace = "%SYS"
    do ##class(Security.Users).UnExpireUserPasswords("*")
    
    // create namespace
    do $SYSTEM.OBJ.Load("/irisdev/app/src/Install/Installer.cls", "ck")
    do ##class(Install.Installer).Install()
    
    // import source code & schemas
    set $namespace = "IRISAPP"
    do $SYSTEM.OBJ.Load("/irisdev/app/src/Oliver/NewProduction.cls", "ck")
